# Generated by Django 4.2.5 on 2023-10-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='text',
        ),
    ]
