# Generated by Django 4.2.5 on 2023-10-15 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_customuser_text'),
        ('main', '0006_customuser_password_01'),
    ]

    operations = [
    ]
